version: '3'

services:
  with-docker-multi-env-production:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: with-docker-multi-env-production
    restart: always
    ports:
      - '3000:3000'
